#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
export PATH="/home/rharison/.nvm/versions/node/v14.19.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
yarn type-check && yarn lint
